---
# Source: onos-classic/templates/configmap-init.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-onos-classic-init-scripts
  labels:
    app: "onos-classic"
    chart: "onos-classic-0.1.31"
    release: "release-name"
    heritage: "Helm"
data:
  configure-onos.sh: |
    #!/usr/bin/env bash

    HOST=`hostname -s`
    DOMAIN=`hostname -d`
    ID=onos-`hostname -s | awk -F '-' '{print $NF}'`

    function print_config() {
        echo "{"
        print_name
        print_node
        print_storage
        echo "}"
    }

    function print_name() {
        echo "  \"name\": \"atomix\","
    }

    function print_node() {
        echo "  \"node\": {"
        echo "    \"id\": \"$ID\","
        echo "    \"host\": \"$HOST.$DOMAIN\","
        echo "    \"port\": 9876"
        echo "  },"
    }

    function print_storage() {
        echo "  \"storage\": ["
        for (( i=1; i<=$ATOMIX_REPLICAS; i++ ))
        do
            if [ $i -eq $ATOMIX_REPLICAS ]; then
                echo "    {"
                echo "      \"id\": \"$ATOMIX_SERVICE-$((i))\","
                echo "      \"host\": \"$ATOMIX_SERVICE-$((i-1)).$ATOMIX_SERVICE-hs\","
                echo "      \"port\": 5679"
                echo "    }"
            else
                echo "    {"
                echo "      \"id\": \"$ATOMIX_SERVICE-$((i))\","
                echo "      \"host\": \"$ATOMIX_SERVICE-$((i-1)).$ATOMIX_SERVICE-hs\","
                echo "      \"port\": 5679"
                echo "    },"
            fi
        done
        echo "  ]"
    }

    ATOMIX_SERVICE=$1
    ATOMIX_REPLICAS=$2

    until nslookup "$ATOMIX_SERVICE-api" > /dev/null 2>&1; do sleep 2; done;

    print_config
---
# Source: onos-classic/templates/configmap-init.yaml
# SPDX-FileCopyrightText: 2022 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0
