---
# Source: onos-classic/templates/onos-config-loader-permissions.yaml
# Copyright 2021-present Open Networking Foundation
# SPDX-FileCopyrightText: 2022 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0
